on: push
name: 🚀 deploy automatizado (html simples)
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    environment: apps_prd
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{secrets.FTP_HOST}}
        FTP_USERNAME: ${{secrets.FTP_USER}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        LOCAL_DIR: .
        REMOTE_DIR: /srv/${{secrets.FTP_HOST}}/www/${{secrets.APP_FOLDER}}
        METHOD: sftp
        PORT: 22
        ARGS: --verbose          